<template>
  <div class="loadingio-spinner-bean-eater-122nn2ooav1i">
    <div class="ldio-yjl8ntb0m2">
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

@Component({})
export default class VLoader extends Vue {

}
</script>

<style lang="scss">
@keyframes ldio-yjl8ntb0m2-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-yjl8ntb0m2-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-yjl8ntb0m2 > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-yjl8ntb0m2 > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #f8b26a;
  animation: ldio-yjl8ntb0m2-1 1s linear infinite;
  transform-origin: 60px 60px;
}
.ldio-yjl8ntb0m2 > div:nth-child(2) div:nth-child(2) {
  animation: ldio-yjl8ntb0m2-2 1s linear infinite;
}
.ldio-yjl8ntb0m2 > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-yjl8ntb0m2-3 {
  0% {
    transform: translate(190px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(70px, 0);
    opacity: 1;
  }
}
.ldio-yjl8ntb0m2 > div:nth-child(1) {
  display: block;
}
.ldio-yjl8ntb0m2 > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #e15b64;
  animation: ldio-yjl8ntb0m2-3 1s linear infinite;
}
.ldio-yjl8ntb0m2 > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-yjl8ntb0m2 > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-yjl8ntb0m2 > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-122nn2ooav1i {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
  border-radius: 50%;
  box-shadow: 0 0 26px 25px $color-white;
  margin: auto;
  transition: 0.4s all ease;
}
.ldio-yjl8ntb0m2 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-yjl8ntb0m2 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>